extends Node

# GAME
const _HARD_MODE_START: int = 1
const _HOUR_DURATION: int = 5
const _GAME_DURATION_HOURS: int = 60
const _GAME_DURATION_SECONDS: int = _GAME_DURATION_HOURS * _HOUR_DURATION

# COOKIES
const _START_COOKIES: int = 12000
const _LOCATOR_RATE_INCREASE: int = 3
const _DOOR_RATE_INCREASE: int = 6
const _COOKIES_TO_FEED: int = 10

# AI
const _PENGU_MAX_COOKIES: int = 18
const _MOVE_SUCCESS_TIME_MULTI: float = 1.2
const _MOVE_CHANCE: int = 3

# MINIGAME
const _BAG_WAIT: float = 3.0
const _MINIGAME_DURATION: int = 20
const _BUMP_OFFSET: Vector2 = Vector2(130, 75)
const _START_PROGRESS: int = 30
const _PROGRESS_INCREASE: int = 16
const _PROGRESS_DECREASE: int = 13


#####################################
##MUTABLE##
#####################################

# GAME
var HARD_MODE_START = _HARD_MODE_START
var HOUR_DURATION: int = _HOUR_DURATION
var GAME_DURATION_HOURS: int = _GAME_DURATION_HOURS
var GAME_DURATION_SECONDS: int = _GAME_DURATION_SECONDS

# COOKIES
var START_COOKIES: int = _START_COOKIES
var LOCATOR_RATE_INCREASE: int = _LOCATOR_RATE_INCREASE
var DOOR_RATE_INCREASE: int = _DOOR_RATE_INCREASE
var COOKIES_TO_FEED: int = _COOKIES_TO_FEED

# AI
var PENGU_MAX_COOKIES: int = _PENGU_MAX_COOKIES
var MOVE_SUCCESS_TIME_MULTI: float = _MOVE_SUCCESS_TIME_MULTI
var MOVE_CHANCE: int = _MOVE_CHANCE

var MOVE_TIME: FloatRange = FloatRange.new(2.5, 4.0)
var ATTACK_DELAY: FloatRange = FloatRange.new(4, 6.0)

# MINIGAME
var BAG_WAIT = _BAG_WAIT
var BUMP_RANGE: FloatRange = FloatRange.new(0.22, 1.5)
var MINIGAME_DURATION: int = _MINIGAME_DURATION
var BUMP_OFFSET: Vector2 = _BUMP_OFFSET
var START_PROGRESS: int = _START_PROGRESS
var PROGRESS_INCREASE: int = _PROGRESS_INCREASE
var PROGRESS_DECREASE: int = _PROGRESS_DECREASE

func set_hard() -> void:
	Utils.AI_PATHS = Utils.hard_ai_paths
	MOVE_TIME.decrease(1.8)
	ATTACK_DELAY.decrease(5)
	MOVE_CHANCE = 1
	BAG_WAIT = 1.5

func reset() -> void:
	Utils.AI_PATHS = Utils.normal_ai_paths
	
	BUMP_RANGE.reset()
	ATTACK_DELAY.reset()
	MOVE_TIME.reset()

	HARD_MODE_START = _HARD_MODE_START
	HOUR_DURATION = _HOUR_DURATION
	GAME_DURATION_HOURS = _GAME_DURATION_HOURS
	GAME_DURATION_SECONDS = _GAME_DURATION_SECONDS

	START_COOKIES = _START_COOKIES
	LOCATOR_RATE_INCREASE = _LOCATOR_RATE_INCREASE
	DOOR_RATE_INCREASE = _DOOR_RATE_INCREASE
	COOKIES_TO_FEED = _COOKIES_TO_FEED

	PENGU_MAX_COOKIES = _PENGU_MAX_COOKIES
	MOVE_SUCCESS_TIME_MULTI = _MOVE_SUCCESS_TIME_MULTI
	MOVE_CHANCE = _MOVE_CHANCE

	BAG_WAIT = _BAG_WAIT
	MINIGAME_DURATION = _MINIGAME_DURATION
	BUMP_OFFSET = _BUMP_OFFSET
	START_PROGRESS = _START_PROGRESS
	PROGRESS_INCREASE = _PROGRESS_INCREASE
	PROGRESS_DECREASE = _PROGRESS_DECREASE
