extends Node

# GAME
const _HARD_MODE_START: int = 2
const _HOUR_DURATION: int = 100
const _GAME_DURATION_HOURS: int = 6
const _GAME_DURATION_SECONDS: int = _GAME_DURATION_HOURS * _HOUR_DURATION

const _AIR_DECREASE = 100.0/8.0
const _AIR_INCREASE = 100.0/10.0

# COOKIES
const _START_COOKIES: int = 50
const _LOCATOR_RATE_INCREASE: int = 2
const _DOOR_RATE_INCREASE: int = 3
const _COOKIES_TO_FEED: int = 10

const _COOKIE_REWARD = 60
const _TOTAL_BARS = 3
const _FILL_INCREASE_RATE = 50.0
const _FILL_DECREASE_RATE = 6.0
const _FILL_RANGE = 10.0

# AI
const _PENGU_MAX_COOKIES: int = 18
const _MOVE_SUCCESS_TIME_MULTI: float = 1.2
const _MOVE_CHANCE: int = 3

# TRASHY
const _TRASHY_CHANCE = 5
const _TRASHY_ATTACK_DELAY = 3.0
const _TRASHY_DURATION = 2.5

# MINIGAME
const _BAG_WAIT: float = 1.5
const _MINIGAME_DURATION: int = 35
const _BUMP_OFFSET: Vector2 = Vector2(130, 75)
const _START_PROGRESS: int = 30
const _PROGRESS_INCREASE: int = 16
const _PROGRESS_DECREASE: int = 13


#####################################
##MUTABLE##
#####################################

# GAME
var HARD_MODE_START = _HARD_MODE_START
var HOUR_DURATION: int = _HOUR_DURATION
var GAME_DURATION_HOURS: int = _GAME_DURATION_HOURS
var GAME_DURATION_SECONDS: int = _GAME_DURATION_SECONDS

var AIR_INCREASE = _AIR_INCREASE
var AIR_DECREASE = _AIR_DECREASE

# COOKIES
var START_COOKIES: int = _START_COOKIES
var LOCATOR_RATE_INCREASE: int = _LOCATOR_RATE_INCREASE
var DOOR_RATE_INCREASE: int = _DOOR_RATE_INCREASE
var COOKIES_TO_FEED: int = _COOKIES_TO_FEED

var COOKIE_REWARD = _COOKIE_REWARD
var TOTAL_BARS = _TOTAL_BARS
var FILL_INCREASE_RATE = _FILL_INCREASE_RATE
var FILL_DECREASE_RATE = _FILL_DECREASE_RATE
var FILL_RANGE = _FILL_RANGE

# AI
var PENGU_MAX_COOKIES: int = _PENGU_MAX_COOKIES
var MOVE_SUCCESS_TIME_MULTI: float = _MOVE_SUCCESS_TIME_MULTI
var MOVE_CHANCE: int = _MOVE_CHANCE

var MOVE_TIME: FloatRange = FloatRange.new(2.5, 4.0)
var ATTACK_DELAY: FloatRange = FloatRange.new(4, 6.0)

# TRASHY
var TRASHY_ATTACK_DELAY = _TRASHY_ATTACK_DELAY

var TRASHY_ATTACK_RANGE: FloatRange = FloatRange.new(20.0, 35.0)#25.0, 45.0)
var TRASHY_DURATION = _TRASHY_DURATION

var TRASHY_COOLDOWN: FloatRange = FloatRange.new(1.2, 1.5)
var TRASHY_CHANCE = _TRASHY_CHANCE

# JACKSON

var JACKSON_ATTACK_RANGE: FloatRange = FloatRange.new(3, 4)#FloatRange.new(16.5, 34.5)

# MINIGAME
var BAG_WAIT = _BAG_WAIT
var BUMP_RANGE: FloatRange = FloatRange.new(0.22, 1.5)
var MINIGAME_DURATION: int = _MINIGAME_DURATION
var BUMP_OFFSET: Vector2 = _BUMP_OFFSET
var START_PROGRESS: int = _START_PROGRESS
var PROGRESS_INCREASE: int = _PROGRESS_INCREASE
var PROGRESS_DECREASE: int = _PROGRESS_DECREASE

func set_hard() -> void:
	Utils.AI_PATHS = Utils.hard_ai_paths
	MOVE_TIME.decrease(1.8)
	ATTACK_DELAY.decrease(5)
	TRASHY_COOLDOWN.decrease(5)
	TRASHY_ATTACK_RANGE.decrease(3.5)
	JACKSON_ATTACK_RANGE.increase(1.35)
	TRASHY_CHANCE -= 1
	MOVE_CHANCE = 1
	BAG_WAIT = 1.5
	TRASHY_ATTACK_DELAY = 1.25
	
	AIR_DECREASE = 100.0/4.5
	AIR_INCREASE = 100.0/7.5

func reset() -> void:
	Utils.AI_PATHS = Utils.normal_ai_paths
	
	BUMP_RANGE.reset()
	ATTACK_DELAY.reset()
	MOVE_TIME.reset()
	TRASHY_COOLDOWN.reset()
	TRASHY_ATTACK_RANGE.reset()
	JACKSON_ATTACK_RANGE.reset()
	
	AIR_DECREASE = _AIR_DECREASE
	AIR_INCREASE = _AIR_INCREASE

	HARD_MODE_START = _HARD_MODE_START
	HOUR_DURATION = _HOUR_DURATION
	GAME_DURATION_HOURS = _GAME_DURATION_HOURS
	GAME_DURATION_SECONDS = _GAME_DURATION_SECONDS
	
	AIR_INCREASE = _AIR_INCREASE
	AIR_DECREASE = _AIR_DECREASE

	START_COOKIES = _START_COOKIES
	LOCATOR_RATE_INCREASE = _LOCATOR_RATE_INCREASE
	DOOR_RATE_INCREASE = _DOOR_RATE_INCREASE
	COOKIES_TO_FEED = _COOKIES_TO_FEED
	
	COOKIE_REWARD = _COOKIE_REWARD
	TOTAL_BARS = _TOTAL_BARS
	FILL_INCREASE_RATE = _FILL_INCREASE_RATE
	FILL_DECREASE_RATE = _FILL_DECREASE_RATE
	FILL_RANGE = _FILL_RANGE

	PENGU_MAX_COOKIES = _PENGU_MAX_COOKIES
	MOVE_SUCCESS_TIME_MULTI = _MOVE_SUCCESS_TIME_MULTI
	MOVE_CHANCE = _MOVE_CHANCE
	
	TRASHY_CHANCE = _TRASHY_CHANCE
	TRASHY_ATTACK_DELAY = _TRASHY_ATTACK_DELAY
	TRASHY_DURATION = _TRASHY_DURATION

	BAG_WAIT = _BAG_WAIT
	MINIGAME_DURATION = _MINIGAME_DURATION
	BUMP_OFFSET = _BUMP_OFFSET
	START_PROGRESS = _START_PROGRESS
	PROGRESS_INCREASE = _PROGRESS_INCREASE
	PROGRESS_DECREASE = _PROGRESS_DECREASE
