extends Node

enum PENGU_POSITIONS {
	START = 1,
	CROSSROADS = 2,
	
	RIGHT_HALLWAY = 3,
	HALLWAY_BEHIND = 4,
	ROOM_BEHIND = 5,
	
	WINDOW_RIGHT = 6,
	WINDOW_LEFT = 7,
	WINDOW_LEFT_LAY = 8,
	ROOM_TOP_LEFT = 9,
	
	ROOM_LEFT = 11,
	ROOM_BOTTOM_LEFT = 12,
	HALLWAY_BEHIND_2 = 13,
	
	DOOR = 10,
	TABLE = 11,
	PLAYER = 999,
	
	_RL_ALT = 110,
	_RBL_ALT = 120,
	_HB2_ALT = 130,
	_RBH_ALT = 50,
}

const AI_PATHS = {
	PENGU_POSITIONS.START: {PENGU_POSITIONS.CROSSROADS: 1},
	PENGU_POSITIONS.CROSSROADS: {
		PENGU_POSITIONS.RIGHT_HALLWAY: 1,
		PENGU_POSITIONS.WINDOW_RIGHT: 2,
	},
	
	#Behind
	PENGU_POSITIONS.RIGHT_HALLWAY: {PENGU_POSITIONS.HALLWAY_BEHIND: 1},
	PENGU_POSITIONS.HALLWAY_BEHIND: {PENGU_POSITIONS.ROOM_BEHIND: 1},
	PENGU_POSITIONS.ROOM_BEHIND: {
		PENGU_POSITIONS.PLAYER: 2,
		PENGU_POSITIONS.HALLWAY_BEHIND_2: 1
	},
	PENGU_POSITIONS.HALLWAY_BEHIND_2: {PENGU_POSITIONS.ROOM_BOTTOM_LEFT: 1},
	PENGU_POSITIONS.ROOM_BOTTOM_LEFT: {PENGU_POSITIONS.ROOM_LEFT: 1},
	PENGU_POSITIONS.ROOM_LEFT: {PENGU_POSITIONS.DOOR: 1},
	
	#Window
	PENGU_POSITIONS.WINDOW_RIGHT: {PENGU_POSITIONS.WINDOW_LEFT: 1},
	PENGU_POSITIONS.WINDOW_LEFT: {PENGU_POSITIONS.WINDOW_LEFT_LAY: 1},
	PENGU_POSITIONS.WINDOW_LEFT_LAY: {PENGU_POSITIONS.ROOM_TOP_LEFT: 1},
	PENGU_POSITIONS.ROOM_TOP_LEFT: {PENGU_POSITIONS.DOOR: 1},
	
	PENGU_POSITIONS.DOOR: {
		PENGU_POSITIONS.PLAYER: 3,
		PENGU_POSITIONS._RL_ALT: 1,
	},
	
	#Alt Behind
	PENGU_POSITIONS._RL_ALT: {PENGU_POSITIONS._RBL_ALT: 1},
	PENGU_POSITIONS._RBL_ALT: {PENGU_POSITIONS._HB2_ALT: 1},
	PENGU_POSITIONS._HB2_ALT: {PENGU_POSITIONS._RBH_ALT: 1},
	PENGU_POSITIONS._RBH_ALT: {PENGU_POSITIONS.PLAYER: 1}
}
